name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Get repository name
        id: repo
        run: |
          REPO_NAME="${{ github.event.repository.name }}"
          echo "Repository name: $REPO_NAME"
          echo "name=$REPO_NAME" >> $GITHUB_OUTPUT
          echo "BASE_PATH will be: /$REPO_NAME"

      - name: Build
        run: |
          echo "Building with BASE_PATH=/${{ steps.repo.outputs.name }}"
          BASE_PATH_VALUE="/${{ steps.repo.outputs.name }}"
          echo "BASE_PATH will be set to: $BASE_PATH_VALUE"
          export BASE_PATH="$BASE_PATH_VALUE"
          npm run build
          echo "Build completed. Checking output directory..."
          ls -la out/ || echo "out directory not found!"
          if [ -f "out/index.html" ]; then
            echo "✓ index.html found in out/"
          else
            echo "✗ index.html NOT found in out/"
            echo "Contents of out/:"
            ls -la out/ || true
          fi
        env:
          # リポジトリ名をbasePathに設定（例: /Ostle_web）
          # ルートドメイン（username.github.io）でホストする場合は空文字列に変更
          BASE_PATH: /${{ steps.repo.outputs.name }}
          NODE_ENV: production

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './out'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


